#!/bin/bash

# debug
# set -x

# check needed vars
if [[ -z $OPENSHIFT_REPO_DIR ]]; then
	echo "Error: OPENSHIFT_REPO_DIR not defined"
	return 1
fi

if [[ -z $OPENSHIFT_DATA_DIR ]]; then
	echo "Error: OPENSHIFT_DATA_DIR not defined"
	return 1
fi

if [[ -z $OPENSHIFT_TMP_DIR ]]; then
	echo "Error: OPENSHIFT_TMP_DIR not defined"
	return 1
fi

if [[ -z $OPENSHIFT_DIY_LOG_DIR ]]; then
	echo "Error: OPENSHIFT_DIY_LOG_DIR not defined"
	return 1
fi

# version of play framework to dowload and install
VERSION="2.2.1"
DEPS_PARAMS=""
ID=""
PLAY_PARAMS=""

#LOG_FILE="${OPENSHIFT_DIY_LOG_DIR}system.out"
LOG_FILE="${OPENSHIFT_DIY_DIR}logs/system.out"
PLAY_COMMAND="${OPENSHIFT_DATA_DIR}play-${VERSION}/play"

return 0