#!/bin/bash 

# debug
# set -x

PLAY_PATH="${OPENSHIFT_DATA_DIR}play/"

# use tmp file just in case it hangs up
PLAY_ARCH="${OPENSHIFT_DATA_DIR}play.zip"

cd "$OPENSHIFT_DATA_DIR"

if [[ -d $PLAY_PATH ]]; then
	echo "Play 2.2.1 already installed at `pwd`/$PLAY_PATH"
else

	echo "Installing play 2.2.1"

	if [[ -f $PLAY_ARCH ]]; then
		rm $PLAY_ARCH
	fi

	PLAY_URL="http://downloads.typesafe.com/play/2.2.1/play-2.2.1.zip"

	curl -o $PLAY_ARCH $PLAY_URL

	if [[ ! -f $PLAY_ARCH ]]; then
		echo "Error downloading play 2.2.1 from $PLAY_URL"
		exit 1
	fi

	rm -rf $PLAY_PATH
	rm -rf ${OPENSHIFT_DATA_DIR}play-2.2.1/
	unzip "$PLAY_ARCH"
	mv ${OPENSHIFT_DATA_DIR}play-2.2.1/ $PLAY_PATH
	rm $PLAY_ARCH
fi

PLAY_PARAMS=""

PLAY_CONFIG_FILE="${OPENSHIFT_REPO_DIR}conf/openshift.conf"

if [[ -f $PLAY_CONFIG_FILE ]]; then

	function read_conf {
		local key=$1
		local default=$2
		local result=`grep "^$key[ |=]" $PLAY_CONFIG_FILE`

		# key not found
		if [[ -z "$result" ]]; then
			echo $default
		else
			result=`echo "$result" | grep -oP "=.*" | cut -b 1 --complement`
			echo $result
		fi
	}

	PLAY_PARAMS=$(read_conf "openshift.play.params" $PLAY_PARAMS)
fi

return 0